{{ config (
    materialized="table"
)}}

select EMP.EMP_ID,
EMP.EMP_NAME,
EMP.GENDER,
DEPT.DEPT_NAME,
MAX(SALARY.MONTH_YEAR) AS DATE,
SALARY.SALARY from "SOURCE_DB"."PUBLIC"."tbl_employee" AS EMP
INNER JOIN "SOURCE_DB"."PUBLIC"."tbl_department" AS DEPT ON EMP.DEPT_ID=DEPT.DEPT_ID
INNER JOIN "SOURCE_DB"."PUBLIC"."tbl_emp_sal" AS SALARY ON EMP.EMP_ID=SALARY.EMP_ID
GROUP BY EMP.EMP_ID,
EMP.EMP_NAME,
EMP.GENDER,
DEPT.DEPT_NAME,
SALARY.SALARY